### ISSUE TITLE
tests for dog component

### ISSUE THREAD

**Issue by tgrecojs** [ohartman/React-Playground#8]
## Tasks 
- naming - image.js -> Image.js (ImageComponent.js)
- create a seperate folder for each components.
   - add <ComponentName>.js 
   - add <ComponentName>.test.js

### Unit tests
- [ ] write unit tests for the ImageComponent
- [ ] library choice is yours but I suggest either [riteway(https://github.com/paralleldrive/riteway), ava, or tape.
- [ ] add a script in package.json that runs tests.
- [ ] add a script that runs tests and then lints all files if tests are passing
- [ ] add test to the github action deployment pipiline. 

https://github.com/ohartman/React-Playground/blob/b20983ecc844da4067eda24d070e58505a52859b/src/image.jsx#L1-L22

**Comment by tgrecojs** [comment]
https://medium.com/javascript-scene/tdd-the-rite-way-53c9b46f45e3

**Comment by tgrecojs** [comment]
[from https://github.com/paralleldrive/riteway](https://github.com/paralleldrive/riteway?tab=readme-ov-file#testing-react-components)

```js
import React from 'react';
import render from 'riteway/render-component';
import { describe } from 'riteway';

describe('renderComponent', async assert => {
  const $ = render(<div className="foo">testing</div>);

  assert({
    given: 'some jsx',
    should: 'render markup',
    actual: $('.foo').html().trim(),
    expected: 'testing'
  });
});
```
